### ISSUE TITLE
Together 기본 스킨 생성 이후 설정 미작동

### ISSUE THREAD

**Issue by icetea-0224** [xpressengine/plugin-together#2]
Together 플러그인을 설치 한 후 기본 데이터들에서 Header Title, Description을 추가하였으나, 정상적으로 작동하지 않습니다.

**Comment by woongbin** [comment]
headerTitle, headerDescription을 설정하면 저장은 되지만 description의 내용으로 header까지 적용되고 있습니다.

**Comment by woongbin** [comment]
현재 포함되어 있는 installer의 설정 문제로 XE3 기본 테마로 변경후 installer의 기능을 삭제 예정입니다.
