### ISSUE TITLE
내 프로필 수정버튼이 안나타는 현상

### ISSUE THREAD

**Issue by leeyunjin89** [xpressengine/plugin-together#4]
내 프로필 영역에 프로필 더미 이미지만 노출됨

<img width="1106" alt="스크린샷 2019-03-15 오후 12 16 59" src="https://user-images.githubusercontent.com/47970666/54406913-578e1b80-471f-11e9-8aad-63d53630647e.png">

**Comment by woongbin** [comment]
현재 포함되어 있는 installer의 설정 문제로 XE3 기본 테마로 변경후 installer의 기능을 삭제 예정입니다.
