### ISSUE TITLE
게시글 댓글 작성시 첨부파일이 있는경우 간헐적으로 등록이 되지 않음

### ISSUE THREAD

**Issue by leeyunjin89** [xpressengine/plugin-together#5]
<img width="584" alt="스크린샷 2019-03-15 오후 12 30 33" src="https://user-images.githubusercontent.com/47970666/54407106-e8fd8d80-471f-11e9-9d2b-cc0d722db876.png">

**Comment by woongbin** [comment]
comment plugin에서 처리하겠습니다.
